# Generated by Django 4.1.3 on 2022-11-10 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='balance',
            field=models.FloatField(default=0.0, verbose_name='Card Balance'),
        ),
        migrations.AlterField(
            model_name='card',
            name='number',
            field=models.PositiveIntegerField(default=8888, verbose_name='Card Number'),
        ),
        migrations.AlterField(
            model_name='card',
            name='series',
            field=models.PositiveIntegerField(default=0, verbose_name='Card Series'),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('value', models.PositiveIntegerField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.card')),
            ],
            options={
                'ordering': ['-date', '-value'],
            },
        ),
    ]
